### ISSUE TITLE
Update Glider Map Screen Capture

### ISSUE THREAD

**Issue by kknee** [ioos/gliders#19]
On the homepage we show a screen capture of the glider map that links to the map.  It needs to be updated to show the new map header BUT we need some photoshop magic to remove the gliders days ribbon from the screen capture (because that value is dynamic).

**Comment by daf** [comment]
Just use devtools and delete the element before screenshotting.  Ben knows (tm)

**Comment by lukecampbell** [comment]
![screen shot 2016-03-15 at 9 01 43 am](https://cloud.githubusercontent.com/assets/1155163/13778548/ea4f3a6e-ea8c-11e5-99c9-063a998c8725.png)

**Comment by lukecampbell** [comment]
![screen shot 2016-03-15 at 9 01 43 am copy](https://cloud.githubusercontent.com/assets/1155163/13778561/f862efba-ea8c-11e5-9780-ddf174631832.png)
